//
// Created by nicolet on 14/09/17.
//

#ifndef PARALLEL_STRATEGIES_TESTING_TESTDEPFLOWGRAPH_H
#define PARALLEL_STRATEGIES_TESTING_TESTDEPFLOWGRAPH_H


class TestDepFlowGraph {

};


#endif //PARALLEL_STRATEGIES_TESTING_TESTDEPFLOWGRAPH_H
